return {
	Title = "DeGOAT Explorer",
	ToggleKey = Enum.KeyCode.RightShift,
	InitialSize = UDim2.fromOffset(980, 620),
	ExplorerWidth = 330,
	RowHeight = 22,
	ScreenPadding = 12,
	MinimumWidth = 480,
	MinimumHeight = 300,
	MinimumEditorWidth = 280,
	MobileBreakpointWidth = 760,
	MobileBreakpointHeight = 520,
	StackBreakpointWidth = 620,
	MobileExplorerRatio = 0.34,
	MobileExplorerMin = 180,
	LongPressSeconds = 0.55,
	GestureMoveTolerance = 9,
	ScrollBarThickness = 11,
	ScrollStepRows = 5,
	AutoBytecode = true,
	UseExecutorUI = true,
	IconBaseUrl = "https://raw.githubusercontent.com/TaxD-drop/DexGOAT/refs/heads/main/DeGOATClient/Icons/",
	IconFolder = "DexGOAT/Icons",
	IconAssets = {},
	AutoClassIcons = true,
	RootServices = {
		"Workspace", "Players", "CoreGui", "Lighting", "MaterialService",
		"ReplicatedFirst", "ReplicatedStorage", "ServerScriptService", "ServerStorage",
		"StarterGui", "StarterPack", "StarterPlayer", "Teams", "SoundService",
		"TextChatService", "RobloxPluginGuiService",
	},
	BytecodeAttribute = "DeGOATBytecode",
	BytecodeValueName = "DeGOATBytecode",
}
